from agent_plugin_builder.agent_plugin_builder import CustomFormatter
from agent_plugin_builder.build_options import PlatformDependencyPackagingMethod

CustomFormatter._get_help_string
PlatformDependencyPackagingMethod.AUTODETECT
